from __future__ import annotations

from .config import WorkspaceError

LOCAL_PROJECT_ENTRY = "__tapmaker_project_entry.lua"
LOCAL_USER_ID = 900000001
COMPONENT_TREE_MARKER = "__TAPMAKER_COMPONENT_TREE__"
COMPONENT_TREE_AGENT_PROMPT = (
    "请为这个 TapMaker 项目的 UI 入口补充组件树调试适配：确保使用 "
    "urhox-libs/UI 创建组件并通过 UI.SetRoot(root) 设置根节点；如果项目封装了自定义 "
    "SetRoot 或组件工厂，请在 --inspect 模式下把最终根组件传给原始 UI.SetRoot。"
)

def compile_entry_wrapper(
    entry: str, *, platform_mock: bool, inspector: bool
) -> bytes:
    if not entry.endswith(".lua"):
        raise WorkspaceError(f"本地平台 mock 只支持 Lua 入口：{entry}")
    module = LOCAL_PROJECT_ENTRY.removesuffix(".lua")
    sections = ["-- Generated by tapmaker web. This file is never written to the project."]
    if platform_mock:
        sections.append(f'''local localUserId = {LOCAL_USER_ID}

lobby = {{}}
function lobby.GetMyUserId()
return localUserId
end

local cloudValues = {{}}
clientCloud = {{}}
function clientCloud:Get(key, events)
if events and events.ok then events.ok({{ [key] = cloudValues[key] }}, {{}}) end
end
function clientCloud:Set(key, value, events)
cloudValues[key] = value
if events and events.ok then events.ok() end
end

function GetUserNickname(options)
if options and options.onSuccess then
    options.onSuccess({{ {{ userId = localUserId, nickname = "本地测试玩家" }} }})
end
end

print("[tapmaker-local] platform mock user_id=" .. tostring(localUserId))
''')
    if inspector:
        sections.append(_component_tree_bridge_source())
    sections.append(f'require("{module}")\n')
    return "\n".join(sections).encode("utf-8")


def _component_tree_bridge_source() -> str:
    return f'''local __tapmakerUI = require("urhox-libs/UI")
	local __tapmakerArrays = setmetatable({{}}, {{ __mode = "k" }})
	local __tapmakerMaxComponents = 10000

local function __tapmakerEscape(value)
return value:gsub("\\\\", "\\\\\\\\"):gsub('"', '\\"'):gsub("\\n", "\\\\n"):gsub("\\r", "\\\\r")
end

local function __tapmakerEncode(value)
local kind = type(value)
if kind == "nil" then return "null" end
if kind == "boolean" or kind == "number" then return tostring(value) end
if kind == "string" then return '"' .. __tapmakerEscape(value) .. '"' end
if kind ~= "table" then return '"<' .. __tapmakerEscape(kind) .. '>"' end
local isArray = __tapmakerArrays[value] or #value > 0
local parts = {{}}
if isArray then
    for index = 1, #value do parts[#parts + 1] = __tapmakerEncode(value[index]) end
    return "[" .. table.concat(parts, ",") .. "]"
end
for key, item in pairs(value) do
    parts[#parts + 1] = __tapmakerEncode(tostring(key)) .. ":" .. __tapmakerEncode(item)
end
return "{{" .. table.concat(parts, ",") .. "}}"
end

local function __tapmakerSnapshot(root)
local count = 0
local truncated = false
local categories = {{}}
local function visit(widget)
    if not widget or count >= __tapmakerMaxComponents then
        truncated = true
        return nil
    end
    count = count + 1
    local props = type(widget.props) == "table" and widget.props or {{}}
    local kind = widget._className or "Widget"
    categories[kind] = (categories[kind] or 0) + 1
    local node = {{
        id = props.id or count,
        runtime_id = count,
        type = kind,
        props = {{}},
        children = {{}},
    }}
    __tapmakerArrays[node.children] = true
    for _, key in ipairs({{ "text", "width", "height", "visible" }}) do
        local value = props[key]
        if type(value) == "string" or type(value) == "number" or type(value) == "boolean" then
            node.props[key] = value
        end
    end
    if type(widget.children) == "table" then
        for _, child in ipairs(widget.children) do
            local childNode = visit(child)
            if childNode then node.children[#node.children + 1] = childNode end
        end
    end
    return node
end
local snapshot = visit(root)
return snapshot, count, categories, truncated
end

	local __tapmakerOriginalSetRoot = __tapmakerUI.SetRoot
if type(__tapmakerOriginalSetRoot) == "function" then
__tapmakerUI.SetRoot = function(root, ...)
    local result = __tapmakerOriginalSetRoot(root, ...)
    local snapshot, count, categories, truncated = __tapmakerSnapshot(root)
    if not snapshot then
        local emptyChildren = {{}}
        __tapmakerArrays[emptyChildren] = true
        snapshot = {{ id = 0, type = "UnknownRoot", props = {{}}, children = emptyChildren }}
    end
    print("{COMPONENT_TREE_MARKER}" .. __tapmakerEncode({{
        root = snapshot,
        component_count = count,
        categories = categories,
        truncated = truncated,
    }}))
    return result
end
else
print("[tapmaker-local] WARNING: UI.SetRoot is unavailable; component tree cannot be captured")
end
'''
